### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by KTibow**
I recently announced ha-blueprint:
https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041?u=ktibow
This makes CI use it.

### CODE REVIEW

**Comment by niemyjski** [comment]
Thanks for the pr. Can you please elaborate what benefit this will add. I checked out the link and it wasn't clear off the bat. Will this test this integration starts up, or is it only linting (if so than it seems overkill to load ha for that) and why does it need a GitHub token.

**Comment by KTibow** [comment]
It runs Hassfest (to catch invalid integrations), HACS (to catch invalid HACS integrations), and flake8 (to catch invalid python).

**Comment by niemyjski** [comment]
@nguyer I think we can merge this, I'm a little skeptical about providing a GitHub token without reviewing the add-on source (with my own token). I'm not sure if we should archive this repo now that it's official part of HA

**Comment by KTibow** [comment]
It's not your own token, it's auto-generated by GitHub.

**Comment by nguyer** [comment]
Yeah I've actually just switched to using the built in integration. I'm not sure we need this repo at all anymore.

**Comment by nguyer** [comment]
@KTibow Thanks for your contribution though!

**Comment by KTibow** [comment]
Might as well clean up stale PRs.

**Pull request closed without merging**
