### PR TITLE
Add support for fan direction.  Updates for const implementation.

### PR DESCRIPTION
**Pull request by steve-gombos**
Add support for fan direction.  Dependent on https://github.com/nguyer/bond-home/pull/5

### CODE REVIEW

**Review by niemyjski — APPROVED** [review]
Looks good, I didn't see the device types and action changes being put into bond api, is this recent or are we waiting on these to be merged in before merging this?

**Comment by steve-gombos** [comment]
@niemyjski Yeah, I tagged the dependent change in the bond-home library above that would need to be merged to support this.

**Comment by niemyjski** [comment]
We'll try and get an update pushed in the base lib and get this merged asap

**Comment by niemyjski** [comment]
Thanks for the pr

**Pull request merged**
