### PR TITLE
Feature/shades

### PR DESCRIPTION
**Pull request by bcb2000**
Added support for covers ("shades")
Support is basic at the moment, there are features of shades in Bond that I don't have on my own somfy blinds, so I have not tried to implement by guesswork.  Supported features are Up, Down, and Hold (stop)

### CODE REVIEW

**Comment by nguyer** [comment]
This is great! Thank you!

**Comment by a200462790** [comment]
This is great! When do we think this can be merged?

**Comment by niemyjski** [comment]
LGTM, can we get all these pr's merged

**Comment by nguyer** [comment]
Hey guys, sorry for the radio silence on this lately. I'll take a look at it tonight and see what I can do. Last time I tested this series of changes, I had issues with duplicated fan speeds, and the speed of my fan not actually changing. I'll try to get to the bottom of what's going on.

My Bond hub has also been acting weird lately, so that's been sort of blocking me from making meaningful progress on this. Supposedly it should be getting a firmware update soon that will fix this though...

**Comment by nguyer** [comment]
Closed, due to https://github.com/nguyer/homeassistant-bond-home/pull/11 superseding this PR

**Pull request closed without merging**
